name = "nekolessi-view-counter"
main = "src/index.js"
compatibility_date = "2026-03-13"

[vars]
ALLOWED_ORIGINS = "https://nekolessi.github.io"
VIEW_MIN_INTERVAL_MS = "120000"
REACTION_MIN_INTERVAL_MS = "10000"

[[durable_objects.bindings]]
name = "PROFILE_COUNTER"
class_name = "ProfileCounterDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ProfileCounterDurableObject"]
